$path = "apps/ui/src/App.tsx"
$text = Get-Content $path -Raw
$text = $text.Replace('  const world = research?.world_model;','  const world = research?.world_model;`n  const hermes = research?.hermes;`n  const transfer100 = hermes?.transfer100;`n  const transfer100Gain = transfer100?.statistics?.transfer_gain?.mean;')
$needle = '    <section className="panel full"><div className="panel-title"><div><FlaskConical size={18}/><h2>Learning'
$insert = @'
    <section className="panel full"><div className="panel-title"><div><FlaskConical size={18}/><h2>Hermes — Selective Transfer</h2></div><span className="muted">Shadow / experimental; nenhum roteamento é promovido pela interface</span></div><div className="metric-grid"><Metric label="TRANSFER-100" value={transfer100Gain === undefined ? "—" : `${transfer100Gain >= 0 ? "+" : ""}${(transfer100Gain*100).toFixed(1)} pp`} tone={transfer100Gain !== undefined && transfer100Gain > 0 ? "good" : "warn"} detail={`${transfer100?.completed_seeds?.length || 0}/10 seeds checkpointed`}/><Metric label="ROUTING DECISIONS" value={String(hermes?.routing.reduce((sum, item) => sum + item.decisions, 0) || 0)} tone="violet" detail="USE / ABSTAIN / REJECT"/><Metric label="DISTILLED" value={String(hermes?.distillation.length || 0)} tone="blue" detail="Procedimentos com proveniência"/><Metric label="UTILITY MAE" value={hermes?.utility_calibration.mean_absolute_error === undefined || hermes?.utility_calibration.mean_absolute_error === null ? "—" : hermes.utility_calibration.mean_absolute_error.toFixed(3)} tone="blue" detail="Predito versus observado"/></div><div className="system-grid"><section className="panel"><div className="panel-title"><div><BrainCircuit size={18}/><h2>Routing</h2></div></div><div className="system-list">{hermes?.routing.map(item => <SystemLine key={`${item.task_family}-${item.decision}`} label={`${item.task_family} · ${item.decision} (${item.decisions})`} value={`EEU ${(item.mean_expected_utility*100).toFixed(1)} pp`} good={item.decision === "USE"}/>) || null}{!hermes?.routing.length && <p className="muted">Ainda sem decisões observadas; fallback é ABSTAIN.</p>}</div></section><section className="panel"><div className="panel-title"><div><ShieldCheck size={18}/><h2>Negative Transfer Firewall</h2></div></div><div className="system-list">{hermes?.family_utility.map(item => <SystemLine key={`${item.task_family}-${item.experience_family}`} label={`${item.task_family} ← ${item.experience_family}`} value={`${item.state} · Δ ${(item.mean_delta*100).toFixed(1)} pp`} good={item.state === "PROMOTABLE"}/>) || null}{!hermes?.family_utility.length && <p className="muted">Sem pares promovidos; famílias não validadas permanecem fresh-only.</p>}</div></section></div></section>
'@
$position = $text.IndexOf($needle)
if ($position -lt 0) { throw "Ponto de inserção Hermes não encontrado" }
$text = $text.Insert($position, $insert)
[System.IO.File]::WriteAllText((Resolve-Path $path), $text)
