$path = "apps/ui/src/App.tsx"
$text = Get-Content $path -Raw
$replacement = @'
function ResearchView({research}:{research:ResearchDashboard|null}) {
  const latest = research?.cgfe?.[0]?.result;
  const ablation = research?.ablations?.[0]?.results || [];
  const learn2 = research?.learn2?.[0]?.result?.results || [];
  const transfer = research?.transfer || [];
  const transferMean = transfer.length ? transfer.reduce((total, item) => total + item.transfer_gain, 0) / transfer.length : null;
  const admission = research?.memory_admission;
  const admissionRate = admission?.total ? ((admission.admitted || 0) / admission.total) : null;
  const world = research?.world_model;
  return <div className="research-dashboard">
    <div className="metric-grid"><Metric label="BENCHMARK RUNS" value={String(research?.runs.length || 0).padStart(2,"0")} tone="blue" detail="Execuções persistidas"/><Metric label="LATEST CGFE" value={latest ? `${latest.cgfe >= 0 ? "+" : ""}${(latest.cgfe*100).toFixed(1)} pp` : "—"} tone={latest?.cgfe >= 0 ? "good" : "warn"} detail="Experienced − fresh"/><Metric label="TRANSFER GAIN" value={transferMean === null ? "—" : `${transferMean >= 0 ? "+" : ""}${(transferMean*100).toFixed(1)} pp`} tone={transferMean !== null && transferMean > 0 ? "good" : "warn"} detail="Média das runs registradas"/><Metric label="LEARN-2" value={learn2.length ? `${learn2.length} pontos` : "—"} tone="violet" detail="Curva filtrada por MAS"/></div>
    <section className="panel full"><div className="panel-title"><div><FlaskConical size={18}/><h2>Learning — CGFE(N) filtrado</h2></div><span className="muted">Experiências verificadas, category-compatible e governadas</span></div><div className="table">{learn2.map(point => <div className="table-row" key={point.experience_count}><strong>N = {point.experience_count}</strong><span>fresh {(point.fresh_score*100).toFixed(1)}%</span><span>experienced {(point.experienced_score*100).toFixed(1)}%</span><strong className={point.cgfe >= 0 ? "good-text" : "warn-text"}>Δ {point.cgfe >= 0 ? "+" : ""}{(point.cgfe*100).toFixed(1)} pp</strong></div>)}{!learn2.length && <div className="empty"><FlaskConical size={24}/><p>Aguardando a execução LEARN-2.</p></div>}</div></section>
    <div className="system-grid"><section className="panel"><div className="panel-title"><div><BrainCircuit size={18}/><h2>Self Model</h2></div></div><div className="system-list">{research?.capabilities.slice(0,6).map(item => <SystemLine key={`${item.domain}-${item.task_type}`} label={`${item.domain} · ${item.task_type} (${item.sample_size})`} value={`${(item.calibrated_score*100).toFixed(1)}% ± ${(item.uncertainty*100).toFixed(1)} pp`} good={item.calibrated_score >= 0.5}/>) || null}{!research?.capabilities.length && <p className="muted">Sem estimativas calibradas observadas.</p>}</div></section><section className="panel"><div className="panel-title"><div><Database size={18}/><h2>Memory & Skills</h2></div></div><div className="system-list"><SystemLine label="Admission rate" value={admissionRate === null ? "—" : `${(admissionRate*100).toFixed(1)}%`} good={admissionRate !== null && admissionRate >= 0.6}/><SystemLine label="MAS médio" value={admission?.mean_score === null || admission?.mean_score === undefined ? "—" : `${(admission.mean_score*100).toFixed(1)}%`} good={(admission?.mean_score || 0) >= 0.6}/><SystemLine label="Skills observadas" value={String(research?.skills.length || 0)} good/></div></section></div>
    <div className="system-grid"><section className="panel"><div className="panel-title"><div><Activity size={18}/><h2>World Model</h2></div><span className="muted">shadow only</span></div><div className="system-list"><SystemLine label="Observações" value={String(world?.observations || 0)} good/><SystemLine label="Prediction accuracy" value={world?.prediction_accuracy === null || world?.prediction_accuracy === undefined ? "—" : `${(world.prediction_accuracy*100).toFixed(1)}%`} good={(world?.prediction_accuracy || 0) >= 0.5}/><SystemLine label="Brier score" value={world?.brier_score === null || world?.brier_score === undefined ? "—" : world.brier_score.toFixed(3)} good={(world?.brier_score ?? 1) <= 0.25}/></div></section><section className="panel"><div className="panel-title"><div><FlaskConical size={18}/><h2>Transfer</h2></div><span className="muted">Fresh vs experienced</span></div><div className="system-list">{transfer.slice(0,5).map(item => <SystemLine key={item.id} label={`${item.model_name} · seed ${item.seed}`} value={`Δ ${item.transfer_gain >= 0 ? "+" : ""}${(item.transfer_gain*100).toFixed(1)} pp`} good={item.transfer_gain > 0}/>) }{!transfer.length && <p className="muted">Aguardando Transfer-20.</p>}</div></section></div>
    <section className="panel full"><div className="panel-title"><div><FlaskConical size={18}/><h2>Capability Gain From Experience</h2></div><span className="muted">Mesma seed e modelo; corpus sem contratos privados</span></div>{latest ? <div className="table"><div className="table-row"><strong>Fresh</strong><span>{(latest.fresh_score*100).toFixed(1)}%</span><strong>Experienced</strong><span>{(latest.experienced_score*100).toFixed(1)}%</span><strong>Δ {latest.cgfe >= 0 ? "+" : ""}{(latest.cgfe*100).toFixed(1)} pp</strong></div></div> : <div className="empty"><FlaskConical size={24}/><p>Execute o diagnóstico CGFE para gerar a primeira comparação.</p></div>}</section>
    <section className="panel full"><div className="panel-title"><div><Activity size={18}/><h2>Benchmark Runs</h2></div><span className="muted">UGIB-Lite · score determinístico</span></div><div className="table">{research?.runs.slice(0,10).map(run => <div className="table-row" key={run.id}><div><strong>{run.mode}</strong><small>{run.model_name} · seed {run.seed}</small></div><span>{run.passed}/{run.total}</span><span>{(run.score*100).toFixed(1)}%</span><span>{run.average_latency_ms.toFixed(0)} ms</span></div>)}{!research?.runs.length && <div className="empty"><Activity size={24}/><p>Nenhum benchmark persistido ainda.</p></div>}</div></section>
    <div className="system-grid"><section className="panel"><div className="panel-title"><div><BrainCircuit size={18}/><h2>Model Comparison</h2></div></div><div className="system-list">{research?.model_comparison.map(model => <SystemLine key={model.model_name} label={`${model.model_name} · ${model.runs} runs`} value={`${(model.average_score*100).toFixed(1)}% · ${model.average_latency_ms} ms`} good/>)}{!research?.model_comparison.length && <p className="muted">Aguardando comparações locais.</p>}</div></section><section className="panel"><div className="panel-title"><div><ShieldCheck size={18}/><h2>Ablations & Regression Policy</h2></div></div><div className="system-list">{ablation.map((item:any) => <SystemLine key={item.variant} label={`${item.variant} · ${item.label}`} value={`${(item.score*100).toFixed(1)}% · Δ ${item.delta_vs_c >= 0 ? "+" : ""}${(item.delta_vs_c*100).toFixed(1)} pp`} good={!item.regression}/>)}{!ablation.length && <p className="muted">Aguardando estudo A–F.</p>}</div></section></div>
    <section className="panel full"><div className="panel-title"><div><FlaskConical size={18}/><h2>Diagnostics</h2></div><span className="muted">Contexto médio {research?.context_metrics?.average_input_tokens ?? "—"} tokens · {research?.context_metrics?.calls ?? 0} chamadas</span></div><div className="table">{research?.diagnostics.slice(0,12).map(item => <div className="table-row" key={item.id}><div><strong>{item.experiment}</strong><small>{item.model_name} · seed {item.seed} · {new Date(item.created_at).toLocaleString()}</small></div><span className="mono">{item.artifact_dir.split(/[\\/]/).slice(-2).join("/")}</span></div>)}{!research?.diagnostics.length && <div className="empty"><FlaskConical size={24}/><p>Execute os diagnósticos locais para gerar evidências.</p></div>}</div></section>
  </div>
}
'@
$pattern = 'function ResearchView\([\s\S]*?(?=function TaskInspector)'
if (-not [regex]::IsMatch($text, $pattern)) { throw "ResearchView não encontrado" }
[System.IO.File]::WriteAllText((Resolve-Path $path), [regex]::Replace($text, $pattern, $replacement, 1))
